# Generated by Django 4.2.4 on 2023-08-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_welkin', '0003_user_email_alter_configuration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
